#9: fix ci/cd with database and add test
* #9 fix database migration

* #9 fix[1] database migration

* #9 fix[2] database migration

* #9 fix[3] database migration

* #9 fix[4] database migration

* #9 fix[5] wrong syntax

* #9 update gitignore

* #9 fix[6] wrong path

* #9 update tests to check ports instead of http codes

* #9 add docker container for tests, because cant get access to github runner's localhost

* #9 debug actions

* #9 try to fix path

* #9 try to fix path [1]

* #9 try to fix path [2]

* #9 try to fix: crlf to lf at entrypoint.sh

* #9 add simple healthcheck to taskbench-backend service

* #9 change test to healthcheck from port ping

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -3,19 +3,89 @@ name: CI
 on:
   push:
     branches:
-      - backend-django
+      - 'backend-django'
   pull_request:
     branches:
-      - backend-django
+      - 'backend-django'
 
 jobs:
-  build-push-deploy:
+  test:
     runs-on: ubuntu-latest
     environment: main
 
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Create test env file
+        run: |
+          cat <<EOF > backend/.env
+          DJANGO_SECRET_KEY=TEST_KEY
+          DEBUG=True
+          DJANGO_LOGLEVEL=info
+          DJANGO_ALLOWED_HOSTS=localhost,0.0.0.0
+          DATABASE_NAME=test_db
+          DATABASE_USERNAME=test_db_user
+          DATABASE_PASSWORD=test_db_password
+          DATABASE_HOST=database
+          DATABASE_PORT=5432
+          GIGACHAT_AUTH_KEY=${{ secrets.GIGACHAT_AUTH_KEY }}
+          EOF
+
+      - name: Local deploy for test
+        run: |
+          cd backend
+          docker compose -f docker-compose.yaml -f docker-compose.override.yaml up --build -d
+          docker compose logs --tail=20
+          
+      - name: Wait for containers to be healthy
+        run: |
+          TIMEOUT=60
+          INTERVAL=2
+          ELAPSED=0
+      
+          echo "Waiting for all services to become healthy..."
+          while [ $ELAPSED -lt $TIMEOUT ]; do
+            STATUS=$(docker inspect --format '{{json .State.Health.Status}}' $(docker compose ps -q) | grep -v "healthy" || true)
+            if [ -z "$STATUS" ]; then
+              echo "All services are healthy!"
+              exit 0
+            fi
+            sleep $INTERVAL
+            ELAPSED=$((ELAPSED + INTERVAL))
+          done
+      
+          echo "Some services did not become healthy in time:"
+          docker compose ps
+          docker compose logs
+          exit 1    
+
+#      - name: Check if app is responding on port (using docker container with tests)
+#        run: |
+#          cd backend
+#          if docker compose logs --tail=20 test | grep -q "success"; then
+#            echo "image is ok"
+#            exit 0
+#          else
+#            echo "port connection failed"
+#            docker compose logs test
+#            exit 1
+#          fi
+
+      - name: Tear down containers
+        if: always()
+        run: |
+          cd backend
+          docker compose -f docker-compose.yaml -f docker-compose.override.yaml down -v
+
+  build:
+    runs-on: ubuntu-latest
+    environment: main
+    needs: test
+
+    steps:
     - name: Checkout code
-      uses: actions/checkout@v3
+      uses: actions/checkout@v4
 
     - name: Create Env file
       run: |
