#9 add docker container for tests, because cant get access to github runner's localhost

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -36,18 +36,19 @@ jobs:
         run: |
           cd backend
           docker compose -f docker-compose.yaml -f docker-compose.override.yaml up --build -d
+          docker compose logs --tail=20
 
-      - name: Check if app is responding on port
+      - name: Check if app is responding on port (using docker container with tests)
         run: |
-          sleep 5
-          echo "Waiting for server to be reachable..."
-          for i in {1..10}; do
-            nc -zv 127.0.0.1 8000 && echo "OK: Port is open!" && exit 0
-            echo "Attempt $i: Server not ready yet..."
-            sleep 5
-          done
-          echo "ERROR: Server is not responding on port 8000"
-          exit 1
+          run: |
+          if docker-compose logs --tail=20 test | grep -q "your_success_pattern"; then
+            echo "image is ok"
+            exit 0
+          else
+            echo "port connection failed"
+            docker-compose logs test
+            exit 1
+          fi
 
       - name: Tear down containers
         if: always()
